#print("Hello World!")
#print("Hello Again")
#print("I like typing this.")
#print("This is fun.")
#print('Yay! Printing!.')
#print("I'd much rahter you 'not'.")
#print('I "said" do not touch this!')
print("Yes, yes, denne funktion kender vi fra første semester...")
print("# udkommenér kode...")